language: python
os:
  - linux
#  - windows  # Travis CI does not support python on Windows currently
python:
#  - "3.5"
#  - "3.6"      # current default Python on Travis CI
  - "3.7"       # tests don't work on 3.6 or earlier due to subprocess changes
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
matrix:
  include:
    #  ====== WINDOWS =========
    # Used to find python versions: https://chocolatey.org/packages/python3#versionhistory
    - name: "Python 3.7.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.6
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.2
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest
# command to install dependencies
install:
  - python -m pip install --editable .
# command to run tests
script:
  - pytest -v
